Introduce B009 and B010 (#55)
Using `getattr(x, 'foo')` and `setattr(x, 'foo', 'bar')` are no more
safe than normal property access and probably cause additional confusion
about safety when they are used because without a default `getattr`
raises the same `AttributeError` as dot access. There is also a
performance cost associated with doing attribute access indirectly.

I've added these as separate warnings since they opperate on two
different behaviors but they could probably be combined as a single
"fat" warning without trouble.

Example with `getattr`:

```python
>>> import os
>>> getattr(os, "foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'foo'
```

Example with `setattr`:

```python
>>> os.foo = "bar"
>>> os.foo
'bar'
>>> setattr(os, "baz", "bar")
>>> os.baz
'bar'
```